### ISSUE TITLE
ValueError: batchmean is not a valid value for reduction

### ISSUE THREAD

**Issue by nguyenvulong** [yoshitomo-matsubara/torchdistill#234]
Hello, I tried to reproduce the example of Coco2017 and encountered this error
(please let me know if I need to move this to the Discussion, I am sorry for the previous post as I did not read your `README` carefully)

Thank you!

**Command executed:**
`CUDA_VISIBLE_DEVICES=3  python3 examples/object_detection.py --config configs/sample/coco2017/multi_stage/ft/custom_fasterrcnn_resnet18_fpn_from_fasterrcnn_resnet50_fpn.yaml --log log/coco2017/ft/custom_fasterrcnn_resnet18_fpn_from_fasterrcnn_resnet50_fpn.txt`

**Error log:**
```
2022/07/07 00:07:12     INFO    torchdistill.models.util        [teacher model]
2022/07/07 00:07:12     INFO    torchdistill.models.util        Using the original teacher model
2022/07/07 00:07:13     INFO    torchdistill.models.util        [teacher model]
2022/07/07 00:07:13     INFO    torchdistill.models.util        Using the Teacher4FactorTransfer teacher model
2022/07/07 00:07:13     INFO    torchdistill.models.util        [student model]
2022/07/07 00:07:13     INFO    torchdistill.models.util        Using the Student4FactorTransfer student model
2022/07/07 00:07:13     INFO    torchdistill.models.util        Frozen module(s): {'student_model.backbone.body.bn1', 'student_model.backbone.body.conv1', 'student_model.backbone.body.maxpool', 'student_model.backbone.body.relu'}
2022/07/07 00:07:13     INFO    torchdistill.core.distillation  Loss = 1.0 * OrgLoss + 1000.0 * FTLoss()
2022/07/07 00:07:13     INFO    torchdistill.core.distillation  Freezing the whole teacher model
2022/07/07 00:07:13     INFO    torchdistill.core.distillation  Advanced to stage 2
Traceback (most recent call last):
  File "examples/object_detection.py", line 244, in <module>
    main(argparser.parse_args())
  File "examples/object_detection.py", line 224, in main
    train(teacher_model, student_model, dataset_dict, ckpt_file_path, device, device_ids, distributed, config, args)
  File "examples/object_detection.py", line 178, in train
    train_one_epoch(training_box, device, epoch, log_freq)
  File "examples/object_detection.py", line 72, in train_one_epoch
    loss = training_box(sample_batch, targets, supp_dict)
  File "/home/longnv/.conda/envs/torchdistill2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/longnv/.conda/envs/torchdistill2/lib/python3.7/site-packages/torchdistill/core/distillation.py", line 314, in forward
    total_loss = self.criterion(output_dict, org_loss_dict, targets)
  File "/home/longnv/.conda/envs/torchdistill2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/longnv/.conda/envs/torchdistill2/lib/python3.7/site-packages/torchdistill/losses/custom.py", line 48, in forward
    loss_dict[loss_name] = factor * criterion(student_output_dict, teacher_output_dict, targets)
  File "/home/longnv/.conda/envs/torchdistill2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/longnv/.conda/envs/torchdistill2/lib/python3.7/site-packages/torchdistill/losses/single.py", line 270, in forward
    reduction=self.reduction)
  File "/home/longnv/.conda/envs/torchdistill2/lib/python3.7/site-packages/torch/nn/functional.py", line 3249, in l1_loss
    return torch._C._nn.l1_loss(expanded_input, expanded_target, _Reduction.get_enum(reduction))
  File "/home/longnv/.conda/envs/torchdistill2/lib/python3.7/site-packages/torch/nn/_reduction.py", line 19, in get_enum
    raise ValueError("{} is not a valid value for reduction".format(reduction))
ValueError: batchmean is not a valid value for reduction
```

**Packages:**
```
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2022.4.26=h06a4308_0
  - certifi=2022.6.15=py37h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.3=h5eee18b_3
  - openssl=1.1.1p=h5eee18b_0
  - pip=21.2.2=py37h06a4308_0
  - python=3.7.13=h12debd9_0
  - readline=8.1.2=h7f8727e_1
  - setuptools=61.2.0=py37h06a4308_0
  - sqlite=3.38.5=hc218d9a_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - pip:
    - cython==0.29.30
    - numpy==1.21.6
    - pycocotools==2.0.4
    - python-dateutil==2.8.2
    - pyyaml==6.0
    - six==1.16.0
    - torch==1.12.0
    - torchdistill==0.3.2
    - torchvision==0.13.0
    - typing-extensions==4.3.0
```

**Comment by yoshitomo-matsubara** [comment]
Hi @nguyenvulong 
Thank you for pointing out the issue. `batchmean` should not be used for `FTLoss` class, and I replaced `batchmean` in the yaml file with `mean`.

Just FYI, most of the yaml config files under `configs/sample/` are used for debugging purpose, so you cannot expect good model accuracy a the end of the training unless you tune the hyperparameters.

If you want to reproduce some numbers reported in the torchdistill paper, I'd suggest that you use yaml files under `configs/official/`
