### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'flatten'

### ISSUE THREAD

**Issue by lilujunai** [yoshitomo-matsubara/torchdistill#34]
Hello, I think your project is great, but after I successfully installed torchdistill with pytorch 1.6, I meet the following problem when running. I look forward to your help，thanks~
```
AttributeError: 'dict' object has no attribute 'flatten'
Traceback (most recent call last):
  File "examples/image_classification.py", line 176, in <module>
    main(argparser.parse_args())
  File "examples/image_classification.py", line 158, in main
    distill(teacher_model, student_model, dataset_dict, device, device_ids, distributed, config, args)
  File "examples/image_classification.py", line 121, in distill
    distill_one_epoch(distillation_box, device, epoch, log_freq)
  File "examples/image_classification.py", line 61, in distill_one_epoch
    loss = distillation_box(sample_batch, targets, supp_dict)
  File "/mnt/cephfs/training/users/lilujun/miniconda3/envs/distill/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/cephfs/training/users/lilujun/miniconda3/envs/distill/lib/python3.7/site-packages/torchdistill/core/distillation.py", line 253, in forward
    self.student_model.post_forward(self.student_io_dict)
  File "/mnt/cephfs/training/users/lilujun/miniconda3/envs/distill/lib/python3.7/site-packages/torchdistill/models/special.py", line 422, in post_forward
    embed_outputs = io_dict[self.input_module_path][self.input_module_io].flatten(1)
```

**Comment by yoshitomo-matsubara** [comment]
Hello @lilujunai ,

Thank you for pointing it out!
I found that this was caused by a change on process for I/O dict after my experiments, to support training with DP (in addition to DDP), and somehow forgot to test it.

The issue was resolved in ver. 0.0.2

**Comment by lilujunai** [comment]
Thank you for your help, I have successfully run it now, thanks~
